# fly.toml app configuration file generated for fancy-item on 2024-07-13T08:50:38+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fancy-item'
primary_region = 'sin'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
